language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --coverage-clover "clover"

after_success:
	- wget https://scrutinizer-ci.com/ocular.phar
	- php ocular.phar code-coverage:upload --access-token="bf65000de9ffe8c906966e656e6d2199e5cc8972a57c1b44c2e98679a4e581e7" --format=php-clover coverage.clover